# ??????? 8081 ???? ??
server:
  port: 8081

# JPA?? ???? ??
spring:
  jpa:  # JPA? ???? SQL ??? ??? ??
    show-sql: true
    hibernate: #  Hibernate? ?????? ???? ???? ????? ?????? ??? ??
      ddl-auto: create # create ?? ?? ??????? ??? ? ?????? ???? ?? ????? ??

  h2:
    console:
      enabled: true #  H2 ?????? ??? ???

  datasource:
    driver-class-name: org.h2.Driver # ?????? ???? ???? ??? ??
    url: jdbc:h2:mem:testdb # H2 ?????? ?? URL? ??
    username: sa # ?????? ??? ??? ??
    password: # ?????? ??? ??? ??